In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv("cosmetics.csv")
x=data.iloc[:,:-1]
y=data.iloc[:,4].values

In [3]:
from sklearn.preprocessing import LabelEncoder
lable_en=LabelEncoder()
x=x.apply(LabelEncoder().fit_transform)
print(x)

    Age  Income  Gender  Martial Status
0     1       0       1               1
1     1       0       1               0
2     0       0       1               1
3     2       2       1               1
4     2       1       0               1
5     2       1       0               0
6     0       1       0               0
7     1       2       1               1
8     1       1       0               0
9     2       2       0               1
10    1       2       0               0
11    0       2       1               0
12    0       0       0               1
13    2       2       1               0


In [4]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()
dt.fit(x,y)


DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [5]:
from sklearn.model_selection import cross_val_score
dt_scores=cross_val_score(dt,x,y,cv=3)
dt_scores

array([0.6 , 0.6 , 0.75])

In [6]:
dt_scores.mean()

0.65

In [7]:
x_ex=np.array([1,1,0,0])
y_pred=dt.predict([x_ex])

In [8]:
y_pred

array(['Yes'], dtype=object)

In [9]:
dt_en=DecisionTreeClassifier(criterion="entropy")
dt_en.fit(x,y)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [10]:
dt_scores_en=cross_val_score(dt,x,y,cv=3)
dt_scores_en

array([0.8 , 0.8 , 0.75])

In [11]:
dt_scores_en.mean()

0.7833333333333333

In [12]:
y_pred_en=dt_en.predict([x_ex])
y_pred_en

array(['Yes'], dtype=object)

In [13]:
from sklearn.externals.six import StringIO
from IPython.display import Image
from sklearn.tree import export_graphviz
import pydotplus

C:\Users\ramyajoshi\Anaconda3\lib\site-packages\sklearn\externals\six.py:31: DeprecationWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", DeprecationWarning)


In [14]:
dot_data=StringIO()
export_graphviz(dt,out_file=dot_data,filled=True,rounded=True)
g=pydotplus.graph_from_dot_data(dot_data.getvalue())

In [ ]:
#iris data

In [17]:
from sklearn.datasets import load_iris
iris=load_iris()
x=iris.data
y=iris.target

In [18]:
dt_iris=DecisionTreeClassifier()
dt_iris.fit(x,y)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [19]:
dt_scores_iris=cross_val_score(dt,x,y,cv=3)
dt_scores_iris

array([0.98039216, 0.92156863, 1.        ])

In [20]:
dt_scores_iris.mean()

0.9673202614379085